### ISSUE TITLE
Support web as target

### ISSUE THREAD

**Issue by necolas** [react-native-community/react-native-geolocation#10]
## Describe the Feature

Web support. Given the geolocation API will no longer be hanging off `navigator` in React Native, we would need a web implementation of this module to maintain cross-platform support for geolocation on web.

## Possible Implementations

Native browser implementation that the RN implementation was based upon:
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

cc @EvanBacon

**Comment by michalchudziak** [comment]
My initial idea was to guide users on how to bring back the compatibility with the previous API on their own. There is a short note in README about that:

> If you need to have geolocation API aligned with the browser (cross-platform apps), or want to support backwards compatibility, please consider adding following lines at the root level, for example at the the top of your App.js file (only for react native):

```js
navigator.geolocation = require('@react-native-community/geolocation');
```

What do you think of this approach? What do you think will be more benefitial in your solution?

**Comment by necolas** [comment]
Overriding the browser global is not a good approach

**Comment by EvanBacon** [comment]
I would strongly recommend we stay away from side-effects. Just simply adding web to the existing interface should be fine.

**Comment by michalchudziak** [comment]
@necolas I'm speaking only of native files, browser remains untouched. Anyway, let's do this, anyone wants to submit a PR? It shouldn't take too long.
