### ISSUE TITLE
Program type already present: com.reactnativecommunity.geolocation.BuildConfig

### ISSUE THREAD

**Issue by yerkejs** [react-native-community/react-native-geolocation#107]
iOS works fine, but at android I have this issue. I do not know what to do.

My terminal: 
`
> Task :app:transformClassesWithMultidexlistForRelease FAILED
D8: Program type already present: com.reactnativecommunity.geolocation.BuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.reactnativecommunity.geolocation.BuildConfig

`

**Comment by DanielRiera** [comment]
Hi

1. Create a file on root project with name `react-native.config.js` with this content:

`module.exports = {
    dependencies: {
      '@react-native-community/geolocation': {
        platforms: {
          android: null, // disable Android platform, other platforms will still autolink if provided
        },
      },
    },
  };`

2. Move to android folder and clean project

`cd android`

`./gradlew clean`

3. Run build

`react-native run-android`

**Comment by mudit70** [comment]
I had the same issue, and following instructions above gives me the error in bug https://github.com/react-native-community/react-native-geolocation/issues/69 .

**Comment by kukuandroid** [comment]
@DanielRiera  hi, your solution is not working for me. Any advice?

**Comment by julitroalves** [comment]
In my case I need to comment or remove this line of android/app/build.gradle file:

```
dependencies {
//     implementation project(':@react-native-community_geolocation')
...
}

**Comment by NEVI0** [comment]
@DanielRiera Dude, you saved my ass. Thanks!!!
