### ISSUE TITLE
Permissions and requestAuthorization

### ISSUE THREAD

**Issue by ishigamii** [react-native-community/react-native-geolocation#23]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.3 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Platforms
- Android 

## Versions
- Android: APi 25 nexus 5X (simu)
- "@react-native-community/geolocation": "^1.1.0",
- react-native:"0.55.4",
- react:"16.3.1",

## Description
When you call `Geolocation.requestAuthorization();` from Android you get a error screen. maybe this method is only intended for iOS ? 

## Reproducible Demo
Just adding this line will get it to crash

## Additional Question 
In the documentation you can see : 
```
Android API >= 18 Positions will also contain a mocked boolean to indicate if position was created from a mock provider.

Android API >= 23 Requires an additional step to check for, and request the ACCESS_FINE_LOCATION permission using the PermissionsAndroid API. Failure to do so may result in a hard crash.
```

But as it is the library is asking for the permissions itself so we don't need to do anything more than just call `Geolocation.getCurrentPosition` like in the integrated version from before no ?

Thanks a lot

**Comment by matt-oakes** [comment]
👋

Android permissions can be requested via the [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid) method or using [`react-native-permissions`](https://github.com/yonahforst/react-native-permissions).

There is a discussion in #12 about how to handle permissions in this library.

**Comment by ishigamii** [comment]
@matt-oakes Yes I understand this perfectly though just calling the method the lib seems to ask for the permission without me asking for the permission before hand that's why I don't understand this :s 
I just tried in debug and release on simulator and real device (Android 8.1.0) and still don't see why I have to use PermissionsAndroid, is this optional for other usage ? 

Thanks a lot for your reply and sorry if I misunderstood somethiing

**Comment by matt-oakes** [comment]
Sorry, I don't understand:

* Which method are you calling? Can you send over a full reproducible demo?
* What specific behaviour are you seeing? You mention a crash but you have not posted the details of one.
* What are you expecting to see?

You need to use `PermissionsAndroid` to request runtime permissions on Android 6.0 and higher. This is in addition to having them defined in your `AndroidManifest.xml`. It is an additional confirmation for users for "high risk" permissions. Details are here:

https://developer.android.com/training/permissions/requesting

**Comment by ishigamii** [comment]
The crash I was having is calling `Geolocation.requestAuthorization();` but my answer is just about getting the localisation
Right now I am talking about another subject. I am only using `Geolocation.getCurrentPosition` in my code for a oneshot localisation. And doing so without asking for more permission (with any other library) just by defining it into the `AndroidManifest.xml` the application work perfectly and ask for the permissions when I call this method (in debug and release mode, on simulator and device). I expected a crash or something reading your documentation  that's why I am confused about it :s

**Comment by matt-oakes** [comment]
If this is a different issue, then please open a new one. You also need to provide more detail like a full reproducible demo. Basically the smallest full React Native app which shows the issue. That helps us to know what the issue is and how to solve it.
