### ISSUE TITLE
Missing Purpose String in Info.plist File for NSLocationAlwaysUsageDescription

### ISSUE THREAD

**Issue by ravirajn22** [react-native-community/react-native-geolocation#25]
## Platforms
iOS

## Versions
- react-native: 0.58.4

## Description

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a `NSLocationAlwaysUsageDescription` key with a user-facing purpose string explaining clearly and completely why your app needs the data. 

We get the above warning email from Apple store. I use `LocationWhenInUseUsageDescription` but not  `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription`. In other terms we want location data only when app is in the foreground not in background.

Things i tried
- Added strings for both `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription`. But this library uses the **always permission** when the strings are present, but we don't want those permission.

What is the best way to handle this situation?

**Comment by matt-oakes** [comment]
Thanks for reporting this issue. This is something that is known about and there is an ongoing discussion about it here:

https://github.com/react-native-community/react-native-geolocation/issues/12

For now, there are some alternative libraries in the README which handle the permissions differently. Alternatively, can you use [`react-native-permissions`](https://github.com/yonahforst/react-native-permissions) instead of the `requestPermissions` method in this library.

I'm going to close this in favour of the open issue mentioned above. Let me know if you have any other issues or comments.

**Comment by matt-oakes** [comment]
A PR to help with this issue has been opened here:

https://github.com/react-native-community/react-native-geolocation/pull/26

**Comment by codoffer** [comment]
I am using below code (Location for application usage only, not required for background) but getting email from iOS submission about "Missing Purpose String in Info.plist File for NSLocationAlwaysUsageDescription"

Can you help me? How can I fix this?

`Geolocation.setRNConfiguration({
                skipPermissionRequests: false,
                authorizationLevel: 'whenInUse'
            });`

**Comment by matt-oakes** [comment]
@codoffer Exactly as the message says, you need to add that key, along with a description of why you need location permission, to your Info.plist file

**Comment by codoffer** [comment]
@matt-oakes I am not using location in background. I am using location when app is active only. For this, I am using 'whenInUse' with setRNConfiguration.

Why am I getting email for  NSLocationAlwaysUsageDescription?

**Comment by matt-oakes** [comment]
The library includes code for both "in use" and "always". Apple can't tell if your app is actually calling any of them. It requires that you add the usage strings for all location types. We should update the README to make this clear.

**Comment by RocKhalil** [comment]
@matt-oakes I know this is an old topic, however, Apple are currently rejecting some Apps if the use the `NSLocationAlwaysUsageDescription`.

Any solution for this ?

**Comment by cwilby** [comment]
Awww the automated bot seemed so proud of it's own ego there.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/13686317/159178079-2bb977ea-f3b7-4ca9-9106-b5b4d4cf500d.png">

**Comment by cwilby** [comment]
This stinks of trojan horse.
