### ISSUE TITLE
Fail callback not called when location permission denied

### ISSUE THREAD

**Issue by puckey** [react-native-community/react-native-geolocation#30]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 269.32 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.npm-packages/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
```

## Platforms
Android

## Versions
- Android: 9
- react-native-geolocation: 1.4.0
- react-native: 0.59.1 => 0.59.1 
- react: 16.8.3 => 16.8.3 

## Description
Using `Geolocation.getCurrentPosition` on Android, when the user selects 'deny' when asked for permission to access the device's location, the fail callback is never called:

## Reproducible Demo
```
const getCurrentPosition = () => {
  return new Promise((resolve, reject) => {
    Geolocation.getCurrentPosition(
      ({ coords }) => {
        const { latitude, longitude } = coords;
        resolve({ latitude, longitude });
      },
      err => {
        console.log(err);
        reject(err);
      },
      {
        enableHighAccuracy: false,
        timeout: 3000
      }
    );
  });
};

getCurrentPosition();
```

**Comment by puckey** [comment]
I can verify that this feature is working in version 1.3.0. Perhaps this functionality was broken in this pr: https://github.com/react-native-community/react-native-geolocation/pull/28

**Comment by Taym95** [comment]
I would like to work on this issue if no one is working on it!

**Comment by matt-oakes** [comment]
@Taym95 Sure! Feel free to open a PR with a proposed fix.

**Comment by janicduplessis** [comment]
Looks like the issue is that RN picks up the web file instead the .native one.

Changing the react-native field to `js/index.native.js` fixes the issue for me.

**Comment by matt-oakes** [comment]
@NoemiRozpara or @michalchudziak RE: React Native Web support for Geolocation:

Could you look into what happens if we change the `react-native` field in `package.json` to `js/index.native.js`? Does React Native Web still pick up the correct file? Would it be better to change the native one to `index.js` and have Web as `index.web.js`?

**Comment by matt-oakes** [comment]
PR is open at #32.

**Comment by MaShizhen** [comment]
me too， may be beacuse I'm in china
