### ISSUE TITLE
The module is imported incorrectly

### ISSUE THREAD

**Issue by Jazqa** [react-native-community/react-native-geolocation#31]
## Environment
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      eslint-plugin-react-native: 3.2.1
      react-native-cli: 2.0.1

## Platforms
Android and iOS

## Versions
- react-native-geolocation: 1.4.0
- react-native: 0.59.8

## Description
    import Geolocation from '@react-native-community/geolocation' 

imports the index.js instead of index.native.js, resulting in "method not supported by the browser" errors even on Android and iOS devices

**Comment by matt-oakes** [comment]
Thanks! We're tracking this in #30 and a PR is open at #32.
