### ISSUE TITLE
Typescript typings missing after 1.4.0

### ISSUE THREAD

**Issue by janpe** [react-native-community/react-native-geolocation#33]
## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 700.40 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 27.0.3, 28.0.3, 29.0.0
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 1.0.0

## Platforms

Issue in typings, so not platform related.

## Versions

- Android: -
- iOS: -
- react-native-geolocation: 1.4.0
- react-native: 0.59.8
- react: 16.8.3

## Description

The `typings` directory is missing from `node_modules/@react-native-community/geolocation` after updating to 1.4.0. Works as expected when downgrading back to 1.3.0

**Comment by taoqf** [comment]
Same issue
