### ISSUE TITLE
Android location permission pops up twice in a row

### ISSUE THREAD

**Issue by albullington** [react-native-community/react-native-geolocation#38]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 511.38 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3
      react-native: ^0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-log-ios: 1.0.1
      react-native-version: 2.7.0
      react-native: 0.57.1

## Platforms
Android

## Versions

- Android: 9, 6.0.1
- iOS: N/A
- react-native-geolocation: 1.4.2
- react-native: 0.59.9
- react: 16.8.3

## Description
The permissions alert consistently pops up twice in a row when a user does not have location permissions enabled and answers "deny" on the first alert. 

## Reproducible Demo

Here is the code I'm using to check for location permissions. This is a helper function outside of my main React component library. 

```
const checkLocationPermissions = async () => {
  const location = PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;

  try {
    const granted = await PermissionsAndroid.request( location );
    if ( granted === PermissionsAndroid.RESULTS.GRANTED ) {
      return true;
    }
    return JSON.stringify( granted );
  } catch ( err ) {
    return err;
  }
};
```

Then, in my component, I'm checking for location permissions like this: 

```
requestAndroidPermissions() {
    if ( Platform.OS === "android" ) {
      checkLocationPermissions().then( ( granted ) => {
        if ( granted ) {
          this.getGeolocation();
        } else {
          this.setError( "location" );
        }
      } );
    } else {
      this.getGeolocation();
    }
  }
```

This happens in three different places where I check for location in the app & is consistent across newer and older Android devices.

**Comment by matt-oakes** [comment]
Thanks for reporting this. 

Can you let me know how you are calling your `requestAndroidPermissions` method? If it's inside a component, can you post all of the relevant bits of that component?

Also, I believe that your `granted` check in the `then` of that method will always be true. This is because your helper method will return either `true` or a non-empty string. Because you are not explicitly checking for `true` it will also pass for the non-empty string.

**Comment by albullington** [comment]
Ah good catch, I updated the code to return `false` instead of `JSON.stringify( granted )` and that got rid of the double pop-up issue.

**Comment by matt-oakes** [comment]
Great. Glad you fixed it! JS can be annoying for those subtle issues...

**Comment by vishaal-workhall** [comment]
const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      );

      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('Location permission granted');
        return true;
      } else if (granted === PermissionsAndroid.RESULTS.DENIED) {
        console.log('Location permission denied');
        return false;
      }


i have been using this snippet. But still I'm getting double pop up issues
