### ISSUE TITLE
SDK location not found

### ISSUE THREAD

**Issue by dancomanlive** [react-native-community/react-native-geolocation#41]
## Environment

System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 34.32 MB / 8.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    eslint-plugin-react-native: 3.7.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Platforms
Android

## Versions
brand new project

## Description
"SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/dan/Workspace/app/android/local.properties'."

## Reproducible Demo
react-native run-android

**Comment by dancomanlive** [comment]
This issue was resolved by creating a local.properties files and adding sdk.dir = /Users/USERNAME/Library/Android/sdk Hopefully this issue can be avoided in the future.

**Comment by matt-oakes** [comment]
I'm glad you sorted this!

Just to let you know that it was an issue with you local setup and not related to this library.

**Comment by tarunvella** [comment]
Hi @dancomanlive 

If I update local.properties with my SDK home directory, I am receiving below error.

* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory 'D:\React-native\PROJECTNAME\android\Users\USERNAME\AppData\Local\Android\Sdk' does not exist.
 
Can i know where does this directory is being set in react-native andriod folder?

**Comment by anmoltiwari00** [comment]
yes exactly same thing happening with me

**Comment by mafideju** [comment]
I'm an Ubuntu user, placed my Android/Sdk at home (root) directory.
Then sdk.dir = /home/marciomafideju/Android/Sdk
Same working directory used in the SDK manager available on android studio configuration.

**Comment by Niz47** [comment]
Run this from cmd line:
ANDROID_HOME="C:\Users\1mike12\AppData\Local\Android\sdk" react-native run-android
if still no,
create a local.properties file in the root of your projects directory and add in:
sdk.dir=C:\Users\1mike12\AppData\Local\Android\sdk

**Comment by howzitcal** [comment]
for linux it looks like you need to add `export ANDROID_SDK_ROOT=$ANDROID_HOME` or `export ANDROID_SDK_ROOT="$HOME/Android/Sdk"` in your .bashrc .zshrc in order to get react native to see the variable

**Comment by joaolvcas** [comment]
> This issue was resolved by creating a local.properties files and adding sdk.dir = /Users/USERNAME/Library/Android/sdk Hopefully this issue can be avoided in the future.

this is work for me. make sure your SDK file location path is correct.
