### ISSUE TITLE
Jest + Geolocation = Error

### ISSUE THREAD

**Issue by SergejDK** [react-native-community/react-native-geolocation#44]
## Environment

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.33 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 25, 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Platforms

Jest - Android and iOS working

## Versions

- Android: 28
- iOS: -
- react-native-geolocation: 1.4.2
- react-native: 0.60.3
- react: 16.8.6 

## Description

After adding Geolocation to the Project the tests are working. Import Geolocation and use it somewhere will fail the test. The test is standard of the CLI-Init project.
All other files are the ones which will be generated automatically.
Linking and everthing is right as far as I can tell.

## Reproducible Demo

1. Create a RN-App CLI: `react-native init Repo1`
2. Add RN-Geolocation: yarn add @react-native-community/geolocation
3. Link it
4. Add Geolocation to a View e.g.:
```js
class App extends React.Component {
  
  state = {
		longitude: null,
		latitude: null,
	}

	componentDidMount() {
		//PermissionsAndroid.request(
		//	PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
		//	{
		//	  title: "Location Accessing Permission",
		//	  message: "App needs access to your location"
		//	}
		//);
		Geolocation.getCurrentPosition(
			(success) => {
				this.setState(
					{longitude: success.coords.longitude,
					latitude: success.coords.latitude}
				)
			},
			(err) => {console.log(err);}
		);
	}

	// https://facebook.github.io/react-native/docs/geolocation#getcurrentposition
	render(){
		return (
			<View>
				<Text>Latitude: {this.state.latitude}</Text>
				<Text>Longitude: {this.state.longitude}</Text>
			</View>
		)
	}
  
};
```

Last Step: run `yarn test` and the following Error appears:

```
yarn test
yarn run v1.13.0
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    @react-native-community/geolocation: NativeModule.RNCGeolocation is null. To fix this issue try these steps:
    • Run `react-native link @react-native-community/geolocation` in the project root.
    • Rebuild and re-run the app.
    • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-geolocation

      at Object.<anonymous> (node_modules/@react-native-community/geolocation/lib/commonjs/nativeInterface.js:17:9)
      at Object.<anonymous> (node_modules/@react-native-community/geolocation/lib/commonjs/implementation.native.js:11:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.145s
Ran all test suites.
error Command failed with exit code 1.
```

Githublink for an example: [https://github.com/SergejDK/ReactNativeJestGeolocationRepo](https://github.com/SergejDK/ReactNativeJestGeolocationRepo)

**Comment by lukewalczak** [comment]
Hey @SergejDK 	, you need to mock the `RNCGeolocation` native module. Create a folder `__mocks__` on the root level. Inside already created folder create another folder `@react-native-community` and within that folder create a file called `geolocation.js`, where you have to specify mocks:

```
export default {
  addListener: jest.fn(),
  getCurrentPosition: jest.fn(),
  removeListeners: jest.fn(),
  requestAuthorization: jest.fn(),
  setConfiguration: jest.fn(),
  startObserving: jest.fn(),
  stopObserving: jest.fn()
};
```

Folders structure should look like:
```
.
├── __mocks__/
│   │── @react-native-community/ 
│   	| -- geolocation.js
```

**Comment by SergejDK** [comment]
@lukewalczak 
Thanks that's working! But why do we need to do this?

**Comment by fhenry-tyemill** [comment]
@lukewalczak I would also like to know why this is necessary.

**Comment by geisterfurz007** [comment]
From my understanding loading the library without a mock causes it to attempt to load its native counterpart from either iOS or android. Because you are not running the tests on either of those, this loading causes them to fall. When providing a mock this way however, there is no attempt being made to access something that cannot be accessed.

**Comment by darran-kelinske-fivestars** [comment]
> Hey @SergejDK , you need to mock the `RNCGeolocation` native module. Create a folder `__mocks__` on the root level. Inside already created folder create another folder `@react-native-community` and within that folder create a file called `geolocation.js`, where you have to specify mocks:
> 
> ```
> export default {
>   addListener: jest.fn(),
>   getCurrentPosition: jest.fn(),
>   removeListeners: jest.fn(),
>   requestAuthorization: jest.fn(),
>   setConfiguration: jest.fn(),
>   startObserving: jest.fn(),
>   stopObserving: jest.fn()
> };
> ```
> 
> Folders structure should look like:
> 
> ```
> .
> ├── __mocks__/
> │   │── @react-native-community/ 
> │   	| -- geolocation.js
> ```

hero. thank you!

**Comment by therealemjy** [comment]
@darran-kelinske-fivestars did that work for you on Detox without any further configuration?
I'm trying to mock a node_module using that technic (`react-native-image-crop-picker` in my case) but when I run the tests Detox loads the original module rather than the mock.

**Comment by divyanshu013** [comment]
Perhaps this should be added to readme? Jest is a pretty common testing framework and others might also run into this issue.

**Comment by tmaly1980** [comment]
There really should be a mock file in the package that we simply can call to jest.mock(), so we don't have to memorize the package signature (function names, variables, etc). Especially if that changes! Please re-open and create a mock file for us that can internally be maintained!

**Comment by ajfranzoia** [comment]
For those using https://github.com/Agontuk/react-native-geolocation-service, the mock file should reside here:
```
├── __mocks__/
│   │── react-native-geolocation-service/ 
│   	| -- index.js
```
