### ISSUE TITLE
react-native 0.60.5 - package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by valery-lavrik** [react-native-community/react-native-geolocation#52]
**$ ./gradlew assembleRelease

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot E:\RN\st-react-native\node_modules\react-native\android

> Task :@react-native-community_geolocation:compileReleaseJavaWithJavac FAILED
E:\RN\st-react-native\node_modules\@react-native-community\geolocation\android\src\main\java\com\reactnativecommunity\geolocation\GeolocationModule.java:21: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^**

the situation was fixed by replacing the string
**import android.support.v4.content.ContextCompat;**
on
**import androidx.core.content.ContextCompat;**

**Comment by janicduplessis** [comment]
Published version 2.0.2 that supports RN 0.60
