### ISSUE TITLE
Accuracy in getCurrentPosition

### ISSUE THREAD

**Issue by King2231** [react-native-community/react-native-geolocation#68]
## Ask your Question

I am using the getCurrentPosition() method of the library. I wish to show accuracy of the location in my app. The method returns accuracy but i am unsure the unit of the accuracy. Is it some kind of a percentage or meters(like whatsapp). Kindly help.

**Comment by jani888** [comment]
According to MDN, it should be in meters.

> The GeolocationCoordinates.accuracy read-only property is a strictly positive double representing the accuracy, with a 95% confidence level, of the [GeolocationCoordinates.latitude](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/latitude) and [GeolocationCoordinates.longitude](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/longitude) properties expressed in meters.

https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/accuracy
