### ISSUE TITLE
'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by AdrianMrn** [react-native-community/react-native-geolocation#79]
I tried both the automatic and the manual installations for iOS, but I always get an error `'React/RCTEventEmitter.h' file not found` in `RNCGeolocation.h` when building the project. I've cleaned the build folder, removed and reinstalled my pods, but nothing I do seems to make any difference 😬 when I undo all my changes, the project builds fine.

I'm on react-native@0.61.2 and react@16.9.0

**Comment by AdrianMrn** [comment]
I undid all my changes, followed the automatic installation steps again and this time it seems to build and run fine, I don't think I actually changed anything 🤷‍♂

**Comment by kukuandroid** [comment]
@AdrianMrn  Hi, how you solved this issue ? Mine is still not working

**Comment by AdrianMrn** [comment]
I honestly couldn't tell you @kukuandroid. Like I said, I just retried the installation, and it ended up working 🤷
