### ISSUE TITLE
GeoLoc always returns PERMISSION_DENIED

### ISSUE THREAD

**Issue by sshanzel** [react-native-community/react-native-geolocation#98]
## Platforms
Android is only what i'm doing right now

## Versions

- Android: API 23
- iOS:
- react-native-geolocation: 1.4.2
- react-native: 0.61.5
- react: 16.9.0

## Description
First of all thank you for this package, currently i am using it and it works perfectly, but then when i integrate this with `react-native-geolocation-enabler` and when i call the enabler the result of every call from this package always results to `PERMISSION_DENIED`. I know and i understand that this may not be independently the reason behind the scenes, but how can i get more details from the error? Would there be a way for me to debug this package or get more error info?

## Reproducible Demo
1. Install both package.
2. Run enabler.
3. GetLocation
4. PERMISSION_DENIED

**Comment by dsmalicsi** [comment]
We've encountered this issue before on iOS. On our case, the app's location permission was set to "Never" on the settings. We just have to set it to "Ask next time" and then when we tried it again, it prompted us to grant permission and it worked fine after allowing it. I believe there's a similar setting for Android too.

**Comment by sshanzel** [comment]
I will make sure to check this one out, thank you very much for the info!

**Comment by sshanzel** [comment]
> We've encountered this issue before on iOS. On our case, the app's location permission was set to "Never" on the settings. We just have to set it to "Ask next time" and then when we tried it again, it prompted us to grant permission and it worked fine after allowing it. I believe there's a similar setting for Android too.

I was able to see the issue. Once i have turned on the Location Service, it can't fetch the Loc instantaneously, so i had to set intervals and resolve once fetched.

**Comment by kathirsuresh** [comment]
> > We've encountered this issue before on iOS. On our case, the app's location permission was set to "Never" on the settings. We just have to set it to "Ask next time" and then when we tried it again, it prompted us to grant permission and it worked fine after allowing it. I believe there's a similar setting for Android too.
> 
> I was able to see the issue. Once i have turned on the Location Service, it can't fetch the Loc instantaneously, so i had to set intervals and resolve once fetched.

Can you help me how to set the intervals?

**Comment by sshanzel** [comment]
> 
> > > We've encountered this issue before on iOS. On our case, the app's location permission was set to "Never" on the settings. We just have to set it to "Ask next time" and then when we tried it again, it prompted us to grant permission and it worked fine after allowing it. I believe there's a similar setting for Android too.
> > 
> > I was able to see the issue. Once i have turned on the Location Service, it can't fetch the Loc instantaneously, so i had to set intervals and resolve once fetched.
> 
> Can you help me how to set the intervals?
> 

Create an interval that requests continuously and clear it once it has succeeded fetching the location.
